

### ---------------- RUTAS PARA AUTENTICACIÓN

### Registro de usuario
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "pepelotas13",
  "password": "pepelotas12"
}

### Login de usuario
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "pepelotas13",
  "password": "pepelotas12"
}


### ---------------- RUTAS PARA PROYECTOS

### Crear proyecto
POST http://localhost:3000/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzBiOWUwMWZhYmNmMzM1Mjk5MTJmOCIsInVzZXJuYW1lIjoicGVwZWxvdGFzMTIiLCJpYXQiOjE3MjM5MDY4NDEsImV4cCI6MTcyMzkxMDQ0MX0.e4YBgxvIEqvhQEwB2X6yOFAiGhz6P_3PPcwqd50kgoc
Content-Type: application/json

{
  "name":"Proyecto 1",
  "description":"Descripcion del proyecto 1 de pepelotas12"
}

### Obtener todos los proyectos
GET http://localhost:3000/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzBiY2JjNjhmZmFmZDdhOGVjZmViYiIsInVzZXJuYW1lIjoicGVwZWxvdGFzMTMiLCJpYXQiOjE3MjM5MDcyNzAsImV4cCI6MTcyMzkxMDg3MH0.1AVthWHxiBbh3zSb4iIDovykbdBRzJ8fdokfE665sqg
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzBiOWUwMWZhYmNmMzM1Mjk5MTJmOCIsInVzZXJuYW1lIjoicGVwZWxvdGFzMTIiLCJpYXQiOjE3MjM5MDY4NDEsImV4cCI6MTcyMzkxMDQ0MX0.e4YBgxvIEqvhQEwB2X6yOFAiGhz6P_3PPcwqd50kgoc

### Obtener un proyecto por ID
GET http://localhost:3000/projects/66c0bb37c7bb92e81fd2b26e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzBiOWUwMWZhYmNmMzM1Mjk5MTJmOCIsInVzZXJuYW1lIjoicGVwZWxvdGFzMTIiLCJpYXQiOjE3MjM5MDY4NDEsImV4cCI6MTcyMzkxMDQ0MX0.e4YBgxvIEqvhQEwB2X6yOFAiGhz6P_3PPcwqd50kgoc

### Actualizar un proyecto
PUT http://localhost:3000/projects/66bf8823c300fd6c9bdf8842
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzBiOWUwMWZhYmNmMzM1Mjk5MTJmOCIsInVzZXJuYW1lIjoicGVwZWxvdGFzMTIiLCJpYXQiOjE3MjM5MDY4NDEsImV4cCI6MTcyMzkxMDQ0MX0.e4YBgxvIEqvhQEwB2X6yOFAiGhz6P_3PPcwqd50kgoc
Content-Type: application/json

{
  "name":"Proyecto 3",
  "description":"Descripcion del proyecto 3"
}

### Eliminar un proyecto
DELETE http://localhost:3000/projects/66bf7eb7f306831ecb239453
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzBiOWUwMWZhYmNmMzM1Mjk5MTJmOCIsInVzZXJuYW1lIjoicGVwZWxvdGFzMTIiLCJpYXQiOjE3MjM5MDY4NDEsImV4cCI6MTcyMzkxMDQ0MX0.e4YBgxvIEqvhQEwB2X6yOFAiGhz6P_3PPcwqd50kgoc


### Añadir un colaborador a un proyecto
POST http://localhost:3000/projects/66c0bb37c7bb92e81fd2b26e/collaborators
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzBiOWUwMWZhYmNmMzM1Mjk5MTJmOCIsInVzZXJuYW1lIjoicGVwZWxvdGFzMTIiLCJpYXQiOjE3MjM5MDY4NDEsImV4cCI6MTcyMzkxMDQ0MX0.e4YBgxvIEqvhQEwB2X6yOFAiGhz6P_3PPcwqd50kgoc
Content-Type: application/json

{
  "collaboratorId": "66c0bcbc68ffafd7a8ecfebb"
}



### ---------------- RUTAS PARA TAREAS

### Crear tarea
POST http://localhost:3000/tasks/projects/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzBiOWUwMWZhYmNmMzM1Mjk5MTJmOCIsInVzZXJuYW1lIjoicGVwZWxvdGFzMTIiLCJpYXQiOjE3MjM5MDY4NDEsImV4cCI6MTcyMzkxMDQ0MX0.e4YBgxvIEqvhQEwB2X6yOFAiGhz6P_3PPcwqd50kgoc
Content-Type: application/json

{
  "title": "Tarea 1",
  "description": "Esta es la tarea 1",
  "projectId": "66c0bb37c7bb92e81fd2b26e"
}

### Obtener todas las tareas de un proyecto
GET http://localhost:3000/tasks/projects/66c0bb37c7bb92e81fd2b26e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzBiOWUwMWZhYmNmMzM1Mjk5MTJmOCIsInVzZXJuYW1lIjoicGVwZWxvdGFzMTIiLCJpYXQiOjE3MjM5MDY4NDEsImV4cCI6MTcyMzkxMDQ0MX0.e4YBgxvIEqvhQEwB2X6yOFAiGhz6P_3PPcwqd50kgoc

### Actualizar una tarea
PUT http://localhost:3000/tasks/projects/66bf8bc66591c6ca98d7be51
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzBiOWUwMWZhYmNmMzM1Mjk5MTJmOCIsInVzZXJuYW1lIjoicGVwZWxvdGFzMTIiLCJpYXQiOjE3MjM5MDY4NDEsImV4cCI6MTcyMzkxMDQ0MX0.e4YBgxvIEqvhQEwB2X6yOFAiGhz6P_3PPcwqd50kgoc
Content-Type: application/json

{
  "status":"completed"
}

### Eliminar una tarea
DELETE http://localhost:3000/tasks/projects/66bf8b9e6591c6ca98d7be4e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzBiOWUwMWZhYmNmMzM1Mjk5MTJmOCIsInVzZXJuYW1lIjoicGVwZWxvdGFzMTIiLCJpYXQiOjE3MjM5MDY4NDEsImV4cCI6MTcyMzkxMDQ0MX0.e4YBgxvIEqvhQEwB2X6yOFAiGhz6P_3PPcwqd50kgoc

